---
- name: Create gunicorn service file
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service

- name: Create gunicorn socket file
  template:
    src: gunicorn.socket.j2
    dest: /etc/systemd/system/gunicorn.socket

- name: Ensure gunicorn socket is enabled
  service:
    name: gunicorn.socket
    enabled: yes
    state: started
