version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-

      - run:
          name: Install Dependencies
          command: |
            # Assumes that pipenv is installed by default in the used image
            pipenv install --dev

      - save_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local/share/virtualenvs
      - run:
          name: Run Tests
          command: |
            pipenv run python manage.py test
      - run:
          name: Run Linter
          command: |
            pipenv run flake8
