---
- name: Ensure python3-venv and build tools are installed (build-essential, python3-dev, libpq-dev)
  apt:
    name:
      - python3-venv
      - build-essential
      - python3-dev
      - libpq-dev

- name: Ensure virtualenv is created
  pip:
    name:
      - wheel
      - pip
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_command: "/usr/bin/python3 -m venv"
    state: latest

- name: Ensure pipenv, gunicorn, psycopg2 are installed in the virtualenv
  pip:
    name:
      - pipenv
      - gunicorn
      - psycopg2
    virtualenv: "{{ virtualenv_path }}"
    state: latest
