---
- name: Ensure venv is installed
  apt:
    name:
      - python3-venv

- name: Ensure pipenv, gunicorn, psycopg2 are installed in the virtualenv
  pip:
    name:
      - wheel
      - pipenv
      - gunicorn
      - psycopg2
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_command: "/usr/bin/python3 -m venv"
    state: latest
