
- name: Install requirements
  shell:
    cmd: ". {{ virtualenv_path }}/bin/activate && {{ virtualenv_path }}/bin/pipenv sync --sequential"
    chdir: "{{ project_path }}"

- name: Ensure secrets directory exists
  file:
    path: "{{ secrets_path }}"
    state: directory

- name: Create secret key if missing
  copy:
    force: no  # Do not overwrite existing key file!
    dest: "{{ secrets_path }}/{{ secret_key_file }}"
    content: "{{ lookup('password', '/dev/null length=50') }}"

- name: Run Django migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_module }}"
  notify: reload application

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_module }}"
  notify: reload application

- name: Make sure the media directory exists
  file:
    path: "{{ media_path }}"
    state: directory
    owner: www-data