name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} quadrivium.azurecr.io
    - run: docker pull quadrivium.azurecr.io/tutti:latest
    - run: docker build -t quadrivium.azurecr.io/tutti:latest .
      env:
        DOCKER_BUILDKIT: 1
    - run: docker push quadrivium.azurecr.io/tutti:latest
